---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: webapps
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: shaikmustafa/camp
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
  namespace: webapps
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
